### ISSUE TITLE
[BUG] Export csv doesn't work with a hostgroup in the filters

### ISSUE THREAD

**Issue by bmareau** [centreon/centreon-widget-service-monitoring#121]
**CENTREON 19.04.x
CentOS 7**

Hi,
Export csv doesn't work with a hostgroup in the filters

**To reproduce :** 
1. Create a widget 'service monitoring'
2. Add an hostgroup in filters 
3. Add ' Enable pagination and more actions ' 
4. Try to Export

![Widget](https://user-images.githubusercontent.com/13255513/61615623-bf70e780-ac66-11e9-8e16-e6c4b5711930.png)

This is the error we have : 

![Error](https://user-images.githubusercontent.com/13255513/61615792-327a5e00-ac67-11e9-9e17-cd58faff0081.png)

Regars

**Comment by sc979** [comment]
A fix is available here :
`https://github.com/centreon/centreon-widget-service-monitoring/pull/125`
Regards,
sc979

**Comment by sc979** [comment]
The fix have been validated, merged and cherry-picked on the 18.10, 19.04 and 19.10 branches.
It will be released on the next minor version.
Regards,
sc979
