### ISSUE TITLE
"hide services with UNREACHABLE host" (PARENT HOST CRITICAL -> CHILD UNREACHABLE -> SERVICES NOT SHOWN)

### ISSUE THREAD

**Issue by infra-webcontact** [centreon/centreon-widget-service-monitoring#74]
Hello,
When a parent host is DOWN, the child hosts are UNREACHABLE.
So their services shouldn't appear if the "hide services with DOWN host" case is checked.
Thank you for your work.

**Comment by ritouret** [comment]
Hello
It would be perfect to have these two choices :
hide services with DOWN host
hide services with UNREACHABLE  host

Because i would check only the last one in my Centreon !
